### ISSUE TITLE
Reverse Proxy Setup on Kubernetes

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-k8-proxy-rebuild#2]
The purpose of this task is to implement the Reverse proxy setup (Squid+NGINX+ICAP) inside a Kubernetes node. Currently implemented as a docker compose script here:
https://github.com/k8-proxy/k8-reverse-proxy/tree/develop/stable-src

This Kubernets node should be running multiple pods and has the possibility to be part of a cluster later.

Please check with the delivery manager on which branch to use.

Notes:
Relevant task:
https://github.com/k8-proxy/k8-performance-use-cases/tree/master/upword-devs/son-ha/issue%20%233%20Configure%20a%20pod%20to%20run%20artillery%20tests%20through%20the%20Squid%20proxy%20%26%20ICAP/Kubernetes/SquidProxy

Update (2020-09-22): Target OS: CentOS

**Comment by mahnouman** [comment]
Hello @hongson1981 Please use Ubuntu for now

**Comment by hongson1981** [comment]
Hi @mahnouman 
Noted with thanks, I will work on Ubuntu for it
