### ISSUE TITLE
C-ICAP test with the new ICAP module

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-k8-proxy-rebuild#25]
Modify the C-ICAP server so that instead of calling the CDR engine directly it will execute the ICAP module developed based on the requirements of https://github.com/k8-proxy/s-k8-proxy-rebuild/issues/3 . There are two versions of the ICAP module that we will need to test both of them, one is built with Golang and the other one is built with C#, both needs to be included.

GW C-ICAP implementation can be found here:
https://github.com/filetrust/c-icap

**Comment by azopat** [comment]
i've figured it out how to call the Go or C# codes. They need to do some small changes for a seamless integration with the icap server.
Comment added here https://github.com/k8-proxy/s-k8-proxy-rebuild/issues/3

**Comment by mahnouman** [comment]
Additional comments from @azopat 

We need to change this line:
https://github.com/filetrust/c-icap/blob/master/c-icap-modules/services/gw_rebuild/gw_rebuild.conf#L48 to call the Golang or C# module instead of the CDR engine.

Shared library .so is used by https://github.com/filetrust/c-icap/tree/master/c-icap-modules/services/gw_rebuild/basic_app and is not longer required.

**Comment by mahnouman** [comment]
Additional requirements is to modify the way that C-ICAP server is calling the ICAP plugin (i.e. the Golang or C# app) so we can pass additional parameters to it. One parameter is what was the ICAP mode, either reqmod or respmod, we need to pass this information from C-ICAP to the plugin.
