### ISSUE TITLE
ICAP Module- MinIO & RabbitMQ communication

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-k8-proxy-rebuild#3]
Modify the ICAP module so that it communicates the received files from the proxy to both MinIO and Rabbit MQ, the idea is to create the following flow:

1. ICAP Server will receive the an adaptation request from a proxy.
2. It will extract the file from the request and send it to MinIO and retrieve a MinIO path.
3. It will send a message to the RabbitMW queue with the MinIO path.
4. CDR service will pick up this message, grab the file, sanitize it, place it on MinIO and respond back with either a location of a new file or a no change message.
5. ICAP server should respond back to the proxy with the new file or a no adaptation required message.

The initial (Alpha) release of the web application must meet the following criteria:

1. Be a single Golang application.
2. Hardcoded to submit a file named "example.pdf" from a local directory called "Outgoing" to MinIO and retrieve the URL of it.
3. Submit the URL to a RabbitMQ as a producer.
4. Receive the URL from RabbitMQ as a consumer.
5. Download the URL from MiniIQ and save the file in a local directory called "Incoming"
6. Set a clear Println statements in the code to display what is going on at the console while the application is running and to emphasize these steps mentioned.
7. Create a Video demonstrating the solution while it is working.
8. Provide in a clean clear way instructions in the readme file on how to setup the system, so a tester can proceed testing it.

Bravo release details:
The code implemented in the first first step is picking up the source file from a hardcoded directory and a hardcoded filename, this behavior which was described in step 2 in the Alpha release requirements, needs to be changed to be:
Allow an external application to call our application with arguments which are specifying the input and output file location.

Specifically this application would be https://github.com/filetrust/c-icap which is currently communicating the same way with the old process which we are replacing in a similar manner:
/usr/local/c-icap/bin/c-icap-client -f <full path to source file>  -o <full path to output file> -s gw_test
/usr/local/c-icap/bin/c-icap-client -f <full path to source file>  -o <full path to output file> -s gw_rebuild  

Charlie release details:

1. We need a sort of identifier so the ICAP module knows that a response it receives as a RabbitMQ consumer is related to a specific message that it (The ICAP module) sent earlier as a producer, this requires adding the following fields:
>file-id: GUID (Auto generated).
>source-file-location: MinIO file location
2. Testing the scenario with the C-ICAP server, this task to be detailed with additional instructions.

**Comment by mahnouman** [comment]
@silvanayousry Please try this on ICAPeg

**Comment by mahnouman** [comment]
Hello @mohitsengarr please develop the same but using C# (Linux is the target platform), you may focus on the Alpha release description above, minus the code being in Golang.

**Comment by mohitsengarr** [comment]
> Hello @mohitsengarr please develop the same but using C# (Linux is the target platform), you may focus on the Alpha release description above, minus the code being in Golang.

Sure

**Comment by mahnouman** [comment]
Hello @silvanayousry @mohitsengarr , I updated the task description with the next step, currently titles "Bravo" release

**Comment by mahnouman** [comment]
Looks to be working releases, to be closed.

**Comment by azopat** [comment]
Hi @mohitsengarr  and @silvanayousry 
In order to integrate this seamlessly with the icap server please do the following :  
- Please add a Make file in order to build your code and create a binary file from it
(now for example on the go code i have to do : go run ... , please add a Make file or script which we can use to generate a go binary) - same for the c# project
- The binary should take the input file and output file (just like now for the go code, but please make it to accept flags, like bellow)
binary -i <input_file> -o <output_file> (because that is how icap server will call it)

- Please when it's called and the output_file created, please exit the program. Don't wait as you are doing now

**Comment by mahnouman** [comment]
Thanks @azopat please @silvanayousry and @mohitsengarr work on this, thank you
