### ISSUE TITLE
Golang ICAP server and module combined

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-k8-proxy-rebuild#33]
Based on the code of ICAPeg, please do:
Download ICAPeg.
Remove existing integrations code and its traces in readme file and in the config file.
Add a new and only integration which represents the ICAP plugin, which is the code @silvanayousry and @azopat are working on. Call this new integration Glasswall.

The code at the end should be one integrated code that is functioning as an ICAP server from one end and communicates directly with MinIO and RabbitMQ using AMQP version 1.

Do use the project structure (Not a single main.go) and DO use Golang packages.

**Comment by dtollaku** [comment]
Not relecant anymore
